### ISSUE TITLE
결과 가사들이 개행이 안되고 있음

### ISSUE THREAD

**Issue by mathisverydifficult** [forus-ai/lyrics-front#13]
output_text는 개행 표시가 삽입되어 있으나 반영이 안되고 있음.

**Comment by gyunggyung** [comment]
이거는 예상 수정일이 언제일요 ?~?

**Comment by 2kyung19** [comment]
@gyunggyung https://github.com/forus-ai/lyrics-front/pull/16 수정했습니다~
