### ISSUE TITLE
아이폰 feed에서 answer버튼 눌렀을 때 눌린 것처럼 표시되는 오류

### ISSUE THREAD

**Issue by mathisverydifficult** [forus-ai/lyrics-front#14]
answer버튼을 클릭해서 다음 대답버튼으로 넘어갈 때, 클릭하지 않았음에도 마우스가 올라가진 것처럼 효과가 발생함.

**Comment by 2kyung19** [comment]
@mathisverydifficult  https://github.com/forus-ai/lyrics-front/pull/17 수정했습니다~

**Comment by mathisverydifficult** [comment]
@media 태그 사용하여 모바일 환경과 구분함.
