### ISSUE TITLE
가사 평가 페이지 시작할 때 장르 선택 + 해당 장르에 평가된 값이과 쓸 수 있는 (good + best) 값이 몇 개 있는지

### ISSUE THREAD

**Issue by gyunggyung** [forus-ai/lyrics-front#21]
시작할 때 장르 버튼 누르면 해당 장르만 평가하게 하고 랜덤이면 지금 처럼
![image](https://user-images.githubusercontent.com/26733242/90304857-f9a6ca00-def6-11ea-8fd5-175ae89f64ab.png)

평가된 가사는 이런식으로
![image](https://user-images.githubusercontent.com/26733242/90304843-c95f2b80-def6-11ea-8a7c-d5e2ecc70aed.png)

해주세요~~

**Comment by Yuddomack** [comment]
@gyunggyung 네~

**Comment by Yuddomack** [comment]
@gyunggyung 
변경 완료됐습니다
