### ISSUE TITLE
가사 평가 페이지에서는 로딩창 제거해주세요~

### ISSUE THREAD

**Issue by gyunggyung** [forus-ai/lyrics-front#22]
평가 페이지에는 필요 없지 않나요??

**Comment by Yuddomack** [comment]
@gyunggyung 왜 필요가 없을까요?

**Comment by gyunggyung** [comment]
평가페이지에서는 평가하는 속도가 중요하고 우리끼리 쓰는거라 과부하가 별로 없을 거 같습니다~~!

**Comment by Yuddomack** [comment]
@gyunggyung 

중복 트랜잭션 방지 및 평가자가 자기 요청이 성립이 됐는지 표시하기 위해서 넣어둔 것인데
과부화가 없다면 로딩창도 빠르게 지나갈텐데 평가하는 속도에 영향이 있나요?

**Comment by gyunggyung** [comment]
그렇군요! 저는 속도의 영향이 약간 있는거 같은데 그런 목적이라면 있어도 괜찮을 거 같습니다 :)

**Comment by Yuddomack** [comment]
@gyunggyung 
아 설마 로딩화면이 이거 말씀하신건가요?
![image](https://user-images.githubusercontent.com/41747333/90325696-caa55c80-dfb9-11ea-8f22-1708b62851bf.png)

**Comment by gyunggyung** [comment]
넵 맞아요 ㅎㅎㅎ

**Comment by Yuddomack** [comment]
ㅋㅋㅋㅋ로직은 같은데 로딩 컴포넌트 스타일이 디자인 반영되서 그랬었네요
가사평가에서는 이전 버전처럼 보이게 바꿔두겠습니다

**Comment by gyunggyung** [comment]
엌ㅋㅋ 좋습니다~~~!!

2020년 8월 16일 (일) 오후 12:50, Yuddomack <notifications@github.com>님이 작성:

**Comment by mathisverydifficult** [comment]
기획에는 다시 포함되어 있는데  어떻게 처리하면 될까요?

**Comment by gyunggyung** [comment]
오잉? 어디에 있을까요? 말씀드리고 안해주시면 됩니다 👍

**Comment by mathisverydifficult** [comment]
https://forusai.slack.com/archives/C018XG2FDKL/p1598169976000600

**Comment by gyunggyung** [comment]
참고로 이거는 아래 페이지에 대한 이야기입니다! @mathisverydifficult 아래 페이지는 더 수정하실 필요는 없습니다!

http://34.64.248.183:9000/eval
