### ISSUE TITLE
결과 페이지에 음악 넣기

### ISSUE THREAD

**Issue by gyunggyung** [forus-ai/lyrics-front#23]
https://github.com/forus-ai/song

여기 있는 음악들을 장르에 맞게 넣어야합니다~~!

**Comment by mathisverydifficult** [comment]
![image](https://user-images.githubusercontent.com/45487140/90323032-92405700-df96-11ea-9b6e-c04af30be88c.png)
구현은 했지만  8/16 회의에서 자원에 추가할 지 플랫폼에 업로드해서 재생할 지 결정 후에  최종 수정 예정

**Comment by mathisverydifficult** [comment]
로컬에서는 음악이 재생되지만... 
배포된 서버에서는 재생이 안되는 문제 발견...
