### ISSUE TITLE
디자인 반영 및 수정 사항 

### ISSUE THREAD

**Issue by haesolchoi** [forus-ai/lyrics-front#36]
[20200823_포어스_결과화면_v1.1.pdf](https://github.com/forus-ai/lyrics-front/files/5113702/20200823_._._v1.1.pdf)

지혜님 올려주신 대로 반영해주시면 됩니다! 

그 외에 링크(http://34.64.248.183:9000/) 에서 발견한 몇 가지 수정 사항 요청드릴게요! 

**[메인화면]**
- [x] 오타: "내가 뭍는 말" -> "내가 묻는 말"

**[모달화면]** 
- [ ] 아무것도 선택하지 않고 "의견보내기" 눌러도 작동이 됩니다. 옵션을 선택하지 않으면 작동하지 않도록 할 수 있을까요?

**[결과화면-모달]**
- [x] "의견 보내기" 누르면 -> 로딩 화면이 나오면서 새로운 가사로 바뀝니다. "의견 보내기"에는 가사 새로고침 기능 빼주세요~! 

**[결과화면]**
- [x] "스튜디오 재입장"->Intro 화면 말고 메인 화면으로 가주세요!

- [x] 이제 결과에 장르별 이미지 반영해주세요!!

[완성본.zip](https://github.com/forus-ai/lyrics-front/files/5113706/default.zip)

**[가사 화면]**
- [x] "원래가사로 돌아가기" 버튼 누르면 로딩 화면이 뜨면서 [결과화면]에 원가사가 아닌 새로운 가사가 뜨네요. 원가사로 바로 돌아갈 수 없을까요? 

- [x] 장르 이름 통일 ex) R&B_소울 -> R&B 소울

- [x] 가사 새로고침 "에일리! 다시해보자~" 기능 추가해 주세요!

**[가사화면-모달]**
- [ ] 가사화면 모달에서 "의견보내기" 버튼 누르면, 장르 선택 화면(이전화면)으로 넘어갑니다. 기존 [가사 화면]이 나오게끔 해주세요! 

언제까지 수정 가능할 지 알려주시면 감사하겟습니다 
감사합니다!

**Comment by 2kyung19** [comment]
고생하셨습니다!
이번 주  오후에 일이 있어서 수~목 까지 반영 해보도록 하겠습니다~

**Comment by haesolchoi** [comment]
- [ ] 장르 이름 변경: CCM/종교 -> 종교 

기독교 색채를 덜어내는 것이 좋겠다는 의견이 나왔습니다..그래서 장르 이름을 변경했으면 하는데 가능할까요?

감사합니다........

**Comment by haesolchoi** [comment]
- [ ] [결과 화면] 설명문 개행을 정해보았습니다! 
아래 링크에서 확인해 주세요..! 
https://www.figma.com/file/UjaeW2sRKWMBZWhoP03rq0/Untitled?node-id=0%3A1

**Comment by mathisverydifficult** [comment]
![Screenshot_20200829-005939_Chrome.jpg](https://user-images.githubusercontent.com/45487140/91588565-51cbda80-e993-11ea-98d4-e9a3c9313733.jpg)

접근권한이 막혀있어서 확인이 불가능합니다!
michaelhj123@gmail.com 접근 허용 부탁드려요!

**Comment by haesolchoi** [comment]
> ![Screenshot_20200829-005939_Chrome.jpg](https://user-images.githubusercontent.com/45487140/91588565-51cbda80-e993-11ea-98d4-e9a3c9313733.jpg)
> 
> 접근권한이 막혀있어서 확인이 불가능합니다!
> [michaelhj123@gmail.com](mailto:michaelhj123@gmail.com) 접근 허용 부탁드려요!

앗 지금 바꿨는데 다시 한 번 확인해주시겠어요?

**Comment by mathisverydifficult** [comment]
정상적으로 확인됩니다.😄

**Comment by haesolchoi** [comment]
- [ ] [Intro 화면] 에일리만 발 색이 달라서 혹시 이 이미로 교체해주실 수 있을까요? 
![에일리](https://user-images.githubusercontent.com/69238807/91638575-6d92b780-ea4b-11ea-9f9b-3f1a8a2e6824.png)

**Comment by haesolchoi** [comment]
- [ ] [결과화면] 및 [가사화면] "에일리! 다시 만들어 보자~" 버튼 색 변경
![Image from iOS](https://user-images.githubusercontent.com/69238807/91638708-60c29380-ea4c-11ea-8725-ba11bf17d8b1.jpg)

- [ ] [결과화면] "에일리 다시만들어줘"    --->  "에일리! 다시 만들어 보자~"로 텍스트 통일해주세요! 

- [ ] [결과화면] &  [가사화면] "에일리! 다시 만들어보자~"에 해당 이모티콘도 추가해주세요ㅠ_ㅠ 
![refresh_2](https://user-images.githubusercontent.com/69238807/91638661-0e817280-ea4c-11ea-8931-20c663aac4b7.png)

- [ ] [결과화면] & [가사화면] 좋아요 / 별로 버튼에 이모티콘도 추가해주세요
![like_icon](https://user-images.githubusercontent.com/69238807/91638684-3670d600-ea4c-11ea-9a34-770c3100fe7c.png)
 
감사합니다 !
