### ISSUE TITLE
모바일 환경에서 키보드가 올라왔을 때 처리

### ISSUE THREAD

**Issue by mathisverydifficult** [forus-ai/lyrics-front#42]
![image](https://user-images.githubusercontent.com/45487140/91381924-804a9800-e863-11ea-887c-701879b7376e.png)

작성하는 화면이 보이도록 처리

**Comment by 2kyung19** [comment]
![image](https://user-images.githubusercontent.com/32586712/91642100-86a76280-ea63-11ea-9d99-c359f420840c.png)
![image](https://user-images.githubusercontent.com/32586712/91642101-8909bc80-ea63-11ea-842f-c43514037cb0.png)

아이폰은 이렇게....  키보드 올렸다 내리면 공간이 생깁니다
