### ISSUE TITLE
다시 만들어줘 시 장르정보 갱신여부

### ISSUE THREAD

**Issue by Yuddomack** [forus-ai/lyrics-front#43]
다시 만들어줘 했을때, 가사는 새로 들어온 값으로 바뀌지만

장르나 이미지 부분은 갱신되지 않는데 의도된 현상인지 문의드려요!

![image](https://user-images.githubusercontent.com/41747333/91384528-d7536b80-e869-11ea-94c6-6e63badf4aef.png)

**Comment by 2kyung19** [comment]
@Yuddomack  '다시만들어줘~'는 설문의 결과 값인 mbti에 따라가야한다고 이해해서
같은 장르에 가사만 갱신되도록 구현했습니다

**Comment by Yuddomack** [comment]
@2kyung19 
그럼 remake는 이 api를 사용해서 구현하는게 나을것같은데 어떠실까요?
http://34.64.248.183:9001/swagger/#/lyrics/LyricsController_getLyricByMbtiType

**Comment by Yuddomack** [comment]
@2kyung19 @mathisverydifficult 
해당 스레드에서 협의되었습니다~~

https://forusai.slack.com/archives/C018GPNFNNT/p1598502847001200

**Comment by mathisverydifficult** [comment]
처리되었습니다.
