### ISSUE TITLE
추가 수정 사항,,,

### ISSUE THREAD

**Issue by haesolchoi** [forus-ai/lyrics-front#48]
- [x] [메인화면] text 변경: 인공지능 작사가 에일리(ai.ly)와 나만의 가사 만들어 보기

- [x] [로딩화면] 혹시 로딩화면은 아직 디자인 반영이 안된 걸까요? ...
<img width="353" alt="로딩화면" src="https://user-images.githubusercontent.com/69238807/91728459-1113d180-ebde-11ea-80f8-dce01f84c6f1.PNG">

- [ ] [결과화면] 웹에서는 가사 스크롤이 보이는데, 모바일에서는 스크롤이 안 보이네요...왜 그런걸까요.흐긓ㄱ...
![가사스크롤](https://user-images.githubusercontent.com/69238807/91728548-34d71780-ebde-11ea-8d1f-e63214dd645e.png)

감사합니다!!!

**Comment by mathisverydifficult** [comment]
https://github.com/forus-ai/lyrics-front/pull/49#issue-476552264

**Comment by mathisverydifficult** [comment]
모바일 추가 확인 필요
