### ISSUE TITLE
ssl 적용 시 가사결과페이지가 안나오는 이슈

### ISSUE THREAD

**Issue by syuo7** [forus-ai/lyrics-front#52]
<img width="1381" alt="Screen Shot 2020-09-02 at 5 13 29 PM" src="https://user-images.githubusercontent.com/10344247/91956659-f78a9b00-ed3f-11ea-8dd2-8622fa61aff3.png">

위 이미지와 같이 결과 페이지에서 아래의 에러가 발생합니다.
index.tsx:191 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at index.tsx:191

backend.forus.ai 로 rest api 요청 시 정상작동합니다.
https://backend.forus.ai/api/v1/lyrics/ENTP/100

감사합니다.

**Comment by mathisverydifficult** [comment]
@Yuddomack  다슬님 보통 이렇게 테스트 서버랑 운영서버를 다르게 둘 때는 api 요청도 구분해서 만들어 놓고 
조건이 충족되면 그 api  url을 사용하도록 설정하나요?
