### ISSUE TITLE
좋아요나 별로에요 버튼을 누르면 닉네임이 초기화 됩니다.

### ISSUE THREAD

**Issue by gyunggyung** [forus-ai/lyrics-front#56]
![image](https://user-images.githubusercontent.com/26733242/92142392-b6cd7780-ee4e-11ea-91bd-9d3cbe62d687.png)

프론트 이슈일까요? 백엔드 이슈일까요?

**Comment by mathisverydifficult** [comment]
프론트 이슈입니다.
처리해놓겠습니다.

**Comment by Yuddomack** [comment]
이쯤되면 context api 도입도 고민해볼만 하겠어요!

**Comment by mathisverydifficult** [comment]
그러게요... 관리해야할 변수들이 계속 늘어가네요...?
코드를 더 나누던가 아니면  context api 도입하는게 좋아보이긴 하네요..
