### ISSUE TITLE
소개페이지

### ISSUE THREAD

**Issue by haesolchoi** [forus-ai/lyrics-front#66]
저희 팀과 에일리를 소개하는 페이지 요청드립니다! 
구체적인 디자인은 아래 참고해 주세요! 
[메인페이지 소개페이지 (1).pdf](https://github.com/forus-ai/lyrics-front/files/5183399/1.pdf)

 [소개 화면] 

- [x] 텍스트: 
“에일리는 누구?” #6C6C6C 
아래 텍스트는 #B2B2B2

에일리(ai.ly)는  AI(인공지능)과 lyricist(작사가)의 합성어로,  여러분과 함께 가사를 만들어주는 
인공지능 작사가에요. 

  에일리는 똑똑한 인공지능이어서 여러분이 원하는대로 새로운 가사를 만들어줄 수 있답니다.

 물론 에일리가 나이도 어리고 경험이 부족해서 여러분의 성향을 찾는 것도, 가사를 만드는 것도 익숙하지 않을 수 있어요. 

  하지만 여러분의 의견이 더해지면 에일리가 크게 성장할 수 있답니다. 공유도 많이 해주셔서 다양한 사람의 의견을 듣고 에일리가 쑥쑥 자랄 수 있도록 해주세요!

 에일리를 만든 저희 ForUS.AI 는 인공지능으로 가사, 기사, 소설 등 다양한 텍스트 콘텐츠 제작을 목표로 모인 팀입니다.

 인공지능 작사가 에일리는 저희의 첫 프로젝트예요 :slightly_smiling_face: 앞으로도 선보일 저희의 다양한 서비스 기대해주세요!

- [x] 뒤로가기/스튜디오 입장 버튼 

[메인 화면]

- [x] 에일리 알아보기 버튼 추가 

감사합니다~!

**Comment by mathisverydifficult** [comment]
네 반영하겠습니다~!

**Comment by mathisverydifficult** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45487140/92421286-c92f1480-f1b2-11ea-8b29-3f77a9a00b6a.gif)
